# The URL the site will be built for
base_url = "https://ddtkey.com"
theme = "apollo"
compile_sass = true

default_language = "en"
build_search_index = true
generate_feed = true
author = "Artem Medvedev"

[slugify]
paths_keep_dates = false
paths = "safe"

[markdown]
render_emoji = true
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "ayu-dark", filename = "css/syntax-dark.css" },
    { theme = "ayu-light", filename = "css/syntax-light.css" },
]

[languages.en]
title = "DDtKey"
taxonomies = [
    { name = "tags", feed = true},
]

[languages.ru]
title = "DDtKey"
taxonomies = [
    { name = "tags", feed = true},
]

[extra]
theme = "toggle"
favicon = "/icons/favicon-32x32.png"
toc = true

menu = [
    { name = "/blog", url = "/blog", weight = 1 },
    { name = "/projects", url = "/projects", weight = 2 },
    { name = "/about", url = "/about", weight = 3 },
]

socials = [
    { name = "github", url = "https://github.com/ddtkey", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/ddtkey", icon = "linkedin" },
    { name = "telegram", url = "https://t.me/ddtkey", icon = "telegram" },
    { name = "email", url = "mailto:i@ddtkey", icon = "email" },
    { name = "twitter", url = "https://twitter.com/ddttkey", icon = "x-twitter" },
]

stylesheets = []

[extra.analytics]
enabled = true

[extra.analytics.goatcounter]
user = "ddtkey"

[extra.author]
name = "Artem Medvedev"
homepage = "https://ddtkey.com"